[build]
  functions = "netlify/functions"
  publish = "."

[[redirects]]
  from = "/api/feed/*"
  to = "/.netlify/functions/feed"
  status = 200
  force = true

[[redirects]]
  from = "/api/feed"
  to = "/.netlify/functions/feed"
  status = 200
  force = true

[[redirects]]
  from = "/api/cluster"
  to = "/.netlify/functions/cluster"
  status = 200
  force = true