// Current language
let currentLang = 'bn';
let currentSourceLang = 'bangla'; // tracks which source group is shown

// Language translations
const translations = {
    en: {
        all: 'All',
        national: 'National',
        international: 'International',
        sports: 'Sports',
        tech: 'Tech',
        technology: 'Technology',
        filters: 'Filters',
        filterBySource: 'Filter by Source',
        banglaSources: 'Bangla Sources',
        englishSources: 'English Sources',
        applyFilters: 'Apply Filters',
        clearAll: 'Clear All',
        loadingNews: 'Loading news...',
        previous: 'Previous',
        next: 'Next',
        page: 'Page',
        noNewsAvailable: 'No news available',
        tryAdjusting: 'Try adjusting your filters or check back later',
        unableToLoad: 'Unable to load news',
        makeSureBackend: 'Please make sure the backend server is running',
        clusters: 'Clusters',
        articles: 'articles',
        viewArticles: 'View all articles',
        hideArticles: 'Hide articles',
        sources: 'Sources',
        addedOn: 'Added on',
        trending: 'Trending',
        clusters: 'Clusters',

        articles: 'articles',
        viewAllArticles: 'View all articles',
        hideArticles: 'Hide articles',
        sources: 'sources',
        coveredBy: 'Covered by',
        moreSources: 'more',
        showLess: 'Show Less',
        sources: 'sources',

        today: 'Today in 2 Minutes',
        topStories: 'Top Stories',
        updatedMinAgo: 'Updated minutes ago',
        articles: 'articles',
        sources: 'sources',
        topCoverage: 'Top Coverage',
        viewAllArticles: 'View all headlines',

        coverageAnalysis: 'Coverage Analysis',
        learnMore: 'Learn more',
        howManySources: 'How many sources?',
        differentAngles: 'Different angles?',

        compareHeadlines: 'Compare Headlines Side-by-Side',
        showListView: 'Show List View',
        comparisonInfo: 'Highlighted words show how different outlets frame this story',

        banglaLabel: 'Bangla',
        englishLabel: 'English',

        tagline: 'Many Voices. Your Choice'
    },
    bn: {
        all: 'সব',
        national: 'জাতীয়',
        international: 'আন্তর্জাতিক',
        sports: 'খেলাধুলা',
        tech: 'প্রযুক্তি',
        technology: 'প্রযুক্তি',
        filters: 'ফিল্টার',
        filterBySource: 'সূত্র অনুসারে ফিল্টার করুন',
        banglaSources: 'বাংলা উৎস',
        englishSources: 'ইংরেজি উৎস',
        applyFilters: 'ফিল্টার প্রয়োগ করুন',
        clearAll: 'সব মুছুন',
        loadingNews: 'খবর লোড হচ্ছে...',
        previous: 'আগের',
        next: 'পরবর্তী',
        page: 'পৃষ্ঠা',
        noNewsAvailable: 'কোনো খবর নেই',
        tryAdjusting: 'আপনার ফিল্টার সামঞ্জস্য করুন বা পরে আবার চেষ্টা করুন',
        unableToLoad: 'খবর লোড করা যায়নি',
        makeSureBackend: 'অনুগ্রহ করে নিশ্চিত করুন যে ব্যাকএন্ড সার্ভার চলছে',
        clusters: 'ক্লাস্টার',
        articles: 'নিবন্ধ',
        viewArticles: 'সব নিবন্ধ দেখুন',
        hideArticles: 'নিবন্ধ লুকান',
        sources: 'উৎস',
        addedOn: 'যোগ করা হয়েছে',
        trending: 'জনপ্রিয়',
        clusters: 'ক্লাস্টার',

        trending: 'জনপ্রিয়',
        articles: 'নিবন্ধ',
        viewAllArticles: 'সব নিবন্ধ দেখুন',
        hideArticles: 'নিবন্ধ লুকান',
        sources: 'উৎস',
        coveredBy: 'টি সূত্র',
        moreSources: 'আরও',
        showLess: 'কম দেখান',
        sources: 'সূত্র',

        today: 'আজকের ২ মিনিট',
        topStories: 'শীর্ষ খবর',
        updatedMinAgo: 'মিনিট আগে আপডেট',
        articles: 'নিবন্ধ',
        sources: 'সূত্র',
        topCoverage: 'শীর্ষ কভারেজ',
        viewAllArticles: 'সব নিবন্ধ দেখুন',

        coverageAnalysis: 'কভারেজ বিশ্লেষণ',
        learnMore: 'আরও জানুন',
        howManySources: 'কতগুলি সূত্র?',
        differentAngles: 'ভিন্ন দৃষ্টিকোণ?',

        compareHeadlines: 'শিরোনাম পাশাপাশি তুলনা করুন',
        showListView: 'তালিকা ভিউ দেখান',
        comparisonInfo: 'হাইলাইট করা শব্দগুলি দেখায় বিভিন্ন আউটলেট কীভাবে এই গল্পটি উপস্থাপন করে',

        banglaLabel: 'বাংলা',
        englishLabel: 'ইংরেজি',
    }
};

// News sources organized by language
const NEWS_SOURCES = {
    bangla: {
        api: [
            'Prothom Alo',
            'Kaler Kantho',
            'Daily Noya Diganta',
            'Samakal',
            'Jugantor',
            'Amar Desh',
            'The Daily Ittefaq',
            'Daily Sangram',
            'Bangladesh Pratidin',
            'Bonik Bartha (Bangla)',
            'The Business Standard (Bangla)',
            'Dhaka Tribune',
            'Jagonews24',
            'bd24live',
            'Amar Bangla BD',
            'Risingbd.com',
            'The New Nation (Bangla)',
            'Dhaka Mail',
            'channelionline',
            'Asian Tv Online',
            'Boishakhi Online',
            'khaborwala'
        ],
        en: [
            'Prothom Alo',
            'Kaler Kantho',
            'Daily Noya Diganta',
            'Samakal',
            'Jugantor',
            'Amar Desh',
            'The Daily Ittefaq',
            'Daily Sangram',
            'Bangladesh Pratidin',
            'Bonik Bartha (Bangla)',
            'The Business Standard (Bangla)',
            'Dhaka Tribune',
            'Jagonews24',
            'bd24live',
            'Amar Bangla BD',
            'Risingbd.com',
            'The New Nation (Bangla)',
            'Dhaka Mail',
            'Channel I Online',
            'Asian Tv Online',
            'Boishakhi Online',
            'khaborwala'
        ],
        bn: [
            'প্রথম আলো',
            'কালের কণ্ঠ',
            'নয়া দিগন্ত',
            'সমকাল',
            'জুগান্তর',
            'আমার দেশ',
            'দৈনিক ইত্তেফাক',
            'দৈনিক সংগ্রাম',
            'বাংলাদেশ প্রতিদিন',
            'বণিক বার্তা (বাংলা)',
            'দ্য বিজনেস স্ট্যান্ডার্ড (বাংলা)',
            'ঢাকা ট্রিবিউন',
            'জাগোনিউজ24',
            'বিডি24লাইভ',
            'আমার বাংলা বিডি',
            'রাইজিংবিডি ডটকম',
            'দ্য নিউ নেশন (বাংলা)',
            'ঢাকা মেইল',
            'channelionline',
            'এশিয়ান টিভি অনলাইন',
            'বৈশাখী অনলাইন',
            'খবরওয়ালা'
        ]
    },
    english: {
        api: [
            'Prothom Alo (English)',
            'Bonik Bartha (English)',
            'The Business Standard (English)',
            'The Daily Star',
            'The Financial Times',
            'The Daily Observer',
            'Ars Technica',
            'investinglive.com',
            'Tech Crunch',
            'Wired',
            'The Hacker News',
            'The Verge',
            'The New Age',
            'The New Nation',
            'The Daily Times Of Bangladesh',
            'Bangladesh Post',
            'The Good Morning',
            'The Register',
            'Zeteo',
            'Al Jazeera',
            'BBC News',
            'TRT World',
            'Middle East Eye',
            'Business Insider',
            'Gizmodo',
            'Independent',
            'RT News'
        ],
        en: [
            'Prothom Alo (English)',
            'Bonik Bartha (English)',
            'The Business Standard (English)',
            'The Daily Star',
            'The Financial Times',
            'The Daily Observer',
            'Ars Technica',
            'investinglive.com',
            'Tech Crunch',
            'Wired',
            'The Hacker News',
            'The Verge',
            'The New Age',
            'The New Nation',
            'The Daily Times Of Bangladesh',
            'Bangladesh Post',
            'The Good Morning',
            'The Register',
            'Zeteo',
            'Al Jazeera',
            'BBC News',
            'TRT World',
            'Middle East Eye',
            'Business Insider',
            'Gizmodo',
            'Independent',
            'RT News'
        ],
        bn: [
            'প্রথম আলো (ইংরেজি)',
            'বণিক বার্তা (ইংরেজি)',
            'দ্য বিজনেস স্ট্যান্ডার্ড (ইংরেজি)',
            'দ্য ডেইলি স্টার',
            'দ্য ফিন্যান্সিয়াল টাইমস',
            'দ্য ডেইলি অবজার্ভার',
            'আরস টেকনিকা',
            'ইনভেস্টিং লাইভ ডট কম',
            'টেকক্রাঞ্চ',
            'ওয়্যার্ড',
            'দ্য হ্যাকার নিউজ',
            'দ্য ভার্জ',
            'নিউ এজ',
            'দ্য নিউ নেশন',
            'দ্য ডেইলি টাইমস অফ বাংলাদেশ',
            'দ্য বাংলাদেশ পোস্ট',
            'দ্য গুড মর্নিং ',
            'দ্য রেজিস্টার',
            'জেটিও',
            'আল জাজিরা',
            'বিবিসি নিউজ',
            'টিআরটি ওয়ার্ল্ড',
            'মিডল ইস্ট আই',
            'বিজনেস ইনসাইডার',
            'গিজমোডো',
            'Independent',
            'আরটি নিউজ'
        ]
    }
};